global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'checkpoint'
    static_configs:
      - targets: ['host.docker.internal:9100']
    metrics_path: /metrics

  - job_name: 'ml-service'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
